### ISSUE TITLE
root request

### ISSUE THREAD

**Issue by Ne-haBhatt** [Fakechippies/Praveen-KS-Writeups#1]
Hey, I am trying so hard but unable to get the root password for james@trickster.htb   After 'su root' I am unable to get password because of my system requirements is not full filled. I hope you can help me.

**Comment by Fakechippies** [comment]
So did u find the mysql creds to login in mysql 

![image](https://github.com/user-attachments/assets/f9efd24d-e5d8-44c8-a18d-ff47be8a6904)

After this u gotta login in mysql to get the james's user hash 

![image](https://github.com/user-attachments/assets/57c10786-33de-4b27-b3c6-e2ba8350d44a)

After this u gotta crack james's password with hashcat like so 

![image](https://github.com/user-attachments/assets/28b45a30-05de-4c27-aa46-5cf40b7a6a80)

**Comment by Ne-haBhatt** [comment]
I already got user.txt. I am talking about the password to log in to root.

**Comment by Fakechippies** [comment]
Im confused so the root (after james in the writeup ) im on is not the real root but the docker container's root and we pivot from there 
Also if u need more help send me a DM on discord : https://discord.gg/nPQBKZhy
Confirm here that u sent me a DM and ill close the issue then
